# [wannierise]
# seed_name = "aiida"

read_amn = true

# read the eig file (can be set to false when not disentangling)
read_eig = true

# write $file.optimize.amn at the end
write_optimized_amn = true

# will freeze if either n <= num_frozen or eigenvalue in frozen window
# dis_froz_num = 0 # 1

# dis_froz_win = true
# dis_froz_win_min = -Inf
# dis_froz_win_max = 12

# dis_froz_proj = true
# dis_froz_proj_min
# dis_froz_proj_max

dis_froz_degen = true

# fix_centers = true
# fix_centers_coords = [
#     # angstrom
#     [1.34940, 1.34940, 1.34940],
#     [1.34940, 1.34940, 1.34940],
#     [1.34940, 1.34940, 1.34940],
#     [1.34940, 1.34940, 1.34940],
#     [0.00000, 0.00000, 0.00000],
#     [0.00000, 0.00000, 0.00000],
#     [0.00000, 0.00000, 0.00000],
#     [0.00000, 0.00000, 0.00000],
# ]

# expert/experimental features
# perform a global rotation by a phase factor at the end
do_normalize_phase = false

# randomize initial gauge
do_randomize_gauge = false

# only minimize sum_n <r^2>_n, not sum_n <r^2>_n - <r>_n^2
only_r2 = false
